ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDo_App.urls')),

]

ToDo_App/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='ToDo_App'
urlpatterns=[
    #Home Page
    path('', views.index, name='index'),
    path('new_list/', views.new_list, name='new_list'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ToDo_App/models.py
from django.db import models

# Create your models here.
class List(models.Model):
    '''A list of activities that the user will be doing'''
    title=models.CharField(max_length=200)
    task=models.TextField()
    date_created=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

ToDo_App/forms.py
from django import forms
from django.forms import ModelForm

from . models import *
class ListForm(forms.ModelForm):
    class Meta:
        model=List
        fields= '__all__'

ToDo_App/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import *
from .forms import *

# Create your views here.
def index(request):
    '''The home page for our ToDo app'''
    lists=List.objects.all()

    form=ListForm()

    if request.method=='POST':
        form=ListForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context={'lists':lists, 'form':form}
    return render(request, 'ToDo_App/index.html', context)

def new_list(request):
    """Adding an new list of items"""
    if request.method!='POST':
        form=ListForm()
    else:
        form=ListForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('ToDo_App:index')
    context={'form': form}
    return render(request, 'ToDo_App/new_list.html', context)

ToDo_App/templates/ToDo_App/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>ToDo App</title>
</head>
<body>
    <p>
        <a href="{% url 'ToDo_App:index' %}">Home</a>
    </p>
    <h3>Todo App helps you keep track of all the todo activities and lists.</h3>
    <header>
        {% load static %}
        <img src="{% static "img/nicky.jpg" %}" alt="Header Image" width="500" height="600">
    </header>
    {% block content%} {%endblock content%}
</body>
<footer>
    <p>Nicky &copy;<span>Copyright, 2020</span></p>
</footer>
</html>

ToDo_App/templates/ToDo_App/index.html
{% extends "ToDo_App/base.html" %}
{%block content%}
    <h2>ToDo List</h2>

    {% for list in lists%}
        <div>
            <ul>
                <li>{{list.title}}</li>
                <p>{{list.task}}</p>
                Created on {{list.date_created}}
            </ul> 
        </div>
    {% endfor %}
    <a href="{% url 'ToDo_App:new_list' %}">Add a new list</a>
{%endblock content%}

 

ToDo_App/templates/ToDo_App/new_list.html
{% extends "ToDo_App/base.html" %}
{% block content %}
    <h4>Add a new list:</h4>
    <form action="{% url 'ToDo_App:new_list' %}" method="POST">
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" name="Add List">
    </form>
{% endblock content %}